
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: fangcun2018
    url: jdbc:mysql://sh-cdb-i8inwrdv.sql.tencentcdb.com:63265/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
env:
  test3333
girl:
  name: nanana
  age: 18
