
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: fangcun2018
    url: jdbc:mysql://sh-cdb-i8inwrdv.sql.tencentcdb.com:63265/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    password: guest
    username: guest
  jpa:
    show-sql: true
env:
  test3333
girl:
  name: nanana
  age: 18
