spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: fangcun2018
    url: jdbc:mysql://sh-cdb-i8inwrdv.sql.tencentcdb.com:63265/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  redis:
    host: 92.168.99.100
    port: 6379
